name: Bug Report
about: File a bug report
title: "[Bug]: "
labels: "bug, not sequenced"
issue_body: true
inputs:
- type: textarea
  attributes:
    label: Are you able to reproduce the bug?
    description: If yes, please describe the steps to reproduce
    placeholder: |
      To help us debug this issue, please explain:
      - What you were trying to do (and why)
      - What happened
      - What you expected to happen
      - Steps to reproduce (with as minimal input data as possible)
    required: true
- type: checkboxes
  attributes:
    label: What is the serverity?
    choices:
      - label: Prod meldown
      - label: Medium
      - label: Low
      - label: required checkbox
        required: true
